version: '3.3'
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_74
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
      - "/var/www/html/uploads"
    ports:
      - 8123:80
    environment:
      - mysql_password=${mysql_password}
      - gmail_password=${gmail_password}
      - discord_link=${discord_link}
  websocket:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node_12
    depends_on:
      - db
    ports:
      - 8125:8080
    environment:
      - mysql_password=${mysql_password}
      - NODE_ENV=production
  db:
    container_name: mysql8
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_password}
      MYSQL_DATABASE: kiro
      MYSQL_USER: kiro_user
      MYSQL_PASSWORD: ${mysql_password}
    ports:
      - 6033:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./php/conf_server/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${mysql_password}
    ports:
      - 8124:80
    depends_on:
      - db 
  webinstaller:
    build:
      context: ./webinstaller
    container_name: webinstaller_0
    depends_on:
      - db
    environment:
      - mysql_password=${mysql_password}
  webtest:
    build:
      context: ./webtest
    container_name: webtest_0
    depends_on:
      - db
    environment:
      - mysql_password=${mysql_password}